// <auto-generated />
using System;
using ChatServerWeb.Model.Entity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;

namespace ChatServerWeb.Api.Migrations
{
    [DbContext(typeof(ChatServerDbContext))]
    [Migration("20181113190755_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-preview1-28290")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ChatServerWeb.Model.Entity.ChatGroup", b =>
                {
                    b.Property<string>("GroupId");

                    b.Property<string>("CreatedByUser");

                    b.Property<DateTime>("DateCreated");

                    b.Property<string>("GroupName");

                    b.Property<int>("NumberOfMembers");

                    b.HasKey("GroupId");

                    b.ToTable("ChatGroups");
                });
#pragma warning restore 612, 618
        }
    }
}
